#!/bin/bash
#shellcheck disable=SC2119
usage() {
	cat <<-eot
	 Function: perrno
	 Desc    : Return text of OS or MySQL error codes.
	 Synopsis: perrno errnumber [os|mysql]
	         :   os|mysql  If not specifed, error codes for both OS and MySQL
	         :             are display.
	 Example : perrno 127 os    # returns text of err 127 in OS
	         : perrno 127 mysql # returns text of err 127 in MySQL
	         : perrno 127       # returns texts of err 127 in both OS and MySQL
	         : mysql mydatabase || perrno $? mysql
	eot
	exit 0
}
. e || exit
[[ $1 == '-h' || $1 == '--help' ]] && usage
$PRG "$@"
#fin
